[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_anchor_pdas_sveltekit = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
solana_anchor_pdas_sveltekit = "BtNQxoo46aU5qTKxehPSkfgxKKtJZVL7Evuz9pWhwPvN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/gaylonalfano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
